apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-aws-secret
type: Opaque
data:
  creds: ""
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: kops.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-aws-secret
      key: creds
